<?php

namespace ContainerCwDTNvf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FT1eibrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fT1eibr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fT1eibr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emargerRepository' => ['privates', 'App\\Repository\\EmargerRepository', 'getEmargerRepositoryService', true],
        ], [
            'emargerRepository' => 'App\\Repository\\EmargerRepository',
        ]);
    }
}
