<?php

namespace ContainerCwDTNvf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmargerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.77EmxgH.App\Entity\Emarger' shared service.
     *
     * @return \App\Entity\Emarger
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.77EmxgH": it needs an instance of "App\\Entity\\Emarger" but this type has been excluded in "config/services.yaml".');
    }
}
