<?php

namespace Container9uIPELb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HtGfo11Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HtGfo11' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HtGfo11'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emploiTempsService' => ['privates', 'App\\Service\\EmploiTempsService', 'getEmploiTempsServiceService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'emploiTempsService' => 'App\\Service\\EmploiTempsService',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);
    }
}
