<?php

namespace Container9uIPELb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VRGNNdmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VRGNNdm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VRGNNdm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emarger' => ['privates', '.errored..service_locator.VRGNNdm.App\\Entity\\Emarger', NULL, 'Cannot autowire service ".service_locator.VRGNNdm": it needs an instance of "App\\Entity\\Emarger" but this type has been excluded in "config/services.yaml".'],
        ], [
            'emarger' => 'App\\Entity\\Emarger',
        ]);
    }
}
