<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'civilite' => [parent::class, 'civilite', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'emargers' => [parent::class, 'emargers', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'inscriptions' => [parent::class, 'inscriptions', null],
        "\0".parent::class."\0".'nomNaissance' => [parent::class, 'nomNaissance', null],
        "\0".parent::class."\0".'nomUsuel' => [parent::class, 'nomUsuel', null],
        "\0".parent::class."\0".'numtel' => [parent::class, 'numtel', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'sessions' => [parent::class, 'sessions', null],
        'civilite' => [parent::class, 'civilite', null],
        'email' => [parent::class, 'email', null],
        'emargers' => [parent::class, 'emargers', null],
        'id' => [parent::class, 'id', null],
        'inscriptions' => [parent::class, 'inscriptions', null],
        'nomNaissance' => [parent::class, 'nomNaissance', null],
        'nomUsuel' => [parent::class, 'nomUsuel', null],
        'numtel' => [parent::class, 'numtel', null],
        'password' => [parent::class, 'password', null],
        'prenom' => [parent::class, 'prenom', null],
        'roles' => [parent::class, 'roles', null],
        'sessions' => [parent::class, 'sessions', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
