<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Promotion extends \App\Entity\Promotion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'annee' => [parent::class, 'annee', null],
        "\0".parent::class."\0".'dateDebut' => [parent::class, 'dateDebut', null],
        "\0".parent::class."\0".'dateFin' => [parent::class, 'dateFin', null],
        "\0".parent::class."\0".'formation' => [parent::class, 'formation', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'inscriptions' => [parent::class, 'inscriptions', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'sessions' => [parent::class, 'sessions', null],
        'annee' => [parent::class, 'annee', null],
        'dateDebut' => [parent::class, 'dateDebut', null],
        'dateFin' => [parent::class, 'dateFin', null],
        'formation' => [parent::class, 'formation', null],
        'id' => [parent::class, 'id', null],
        'inscriptions' => [parent::class, 'inscriptions', null],
        'nom' => [parent::class, 'nom', null],
        'sessions' => [parent::class, 'sessions', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
